// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/cliente.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClienteRequest struct {
	Rut                  string   `protobuf:"bytes,1,opt,name=rut,proto3" json:"rut,omitempty"`
	Correo               string   `protobuf:"bytes,2,opt,name=correo,proto3" json:"correo,omitempty"`
	Pdf                  []byte   `protobuf:"bytes,3,opt,name=pdf,proto3" json:"pdf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClienteRequest) Reset()         { *m = ClienteRequest{} }
func (m *ClienteRequest) String() string { return proto.CompactTextString(m) }
func (*ClienteRequest) ProtoMessage()    {}
func (*ClienteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_45e0fa2c3566535f, []int{0}
}

func (m *ClienteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClienteRequest.Unmarshal(m, b)
}
func (m *ClienteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClienteRequest.Marshal(b, m, deterministic)
}
func (m *ClienteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClienteRequest.Merge(m, src)
}
func (m *ClienteRequest) XXX_Size() int {
	return xxx_messageInfo_ClienteRequest.Size(m)
}
func (m *ClienteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClienteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClienteRequest proto.InternalMessageInfo

func (m *ClienteRequest) GetRut() string {
	if m != nil {
		return m.Rut
	}
	return ""
}

func (m *ClienteRequest) GetCorreo() string {
	if m != nil {
		return m.Correo
	}
	return ""
}

func (m *ClienteRequest) GetPdf() []byte {
	if m != nil {
		return m.Pdf
	}
	return nil
}

type ClienteResponse struct {
	Mensaje              string   `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClienteResponse) Reset()         { *m = ClienteResponse{} }
func (m *ClienteResponse) String() string { return proto.CompactTextString(m) }
func (*ClienteResponse) ProtoMessage()    {}
func (*ClienteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_45e0fa2c3566535f, []int{1}
}

func (m *ClienteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClienteResponse.Unmarshal(m, b)
}
func (m *ClienteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClienteResponse.Marshal(b, m, deterministic)
}
func (m *ClienteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClienteResponse.Merge(m, src)
}
func (m *ClienteResponse) XXX_Size() int {
	return xxx_messageInfo_ClienteResponse.Size(m)
}
func (m *ClienteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClienteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClienteResponse proto.InternalMessageInfo

func (m *ClienteResponse) GetMensaje() string {
	if m != nil {
		return m.Mensaje
	}
	return ""
}

func init() {
	proto.RegisterType((*ClienteRequest)(nil), "clientegrpc.ClienteRequest")
	proto.RegisterType((*ClienteResponse)(nil), "clientegrpc.ClienteResponse")
}

func init() {
	proto.RegisterFile("proto/cliente.proto", fileDescriptor_45e0fa2c3566535f)
}

var fileDescriptor_45e0fa2c3566535f = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xcb, 0x4a, 0xc5, 0x30,
	0x18, 0x84, 0xad, 0x85, 0x8a, 0xf1, 0x4a, 0x04, 0x09, 0xea, 0xa2, 0x64, 0x55, 0x10, 0x12, 0xad,
	0x4f, 0xa0, 0x6e, 0xeb, 0xa6, 0xee, 0x5c, 0x08, 0x69, 0xfc, 0xad, 0x11, 0x9b, 0xc4, 0x5c, 0x7c,
	0x7e, 0x69, 0x1a, 0x8b, 0x07, 0xce, 0x2a, 0xf3, 0x4d, 0xc2, 0xcc, 0x10, 0x74, 0x66, 0x9d, 0x09,
	0x86, 0xcb, 0x2f, 0x05, 0x3a, 0x00, 0x4b, 0x84, 0x0f, 0x32, 0x8e, 0xce, 0x4a, 0xda, 0xa1, 0xe3,
	0xc7, 0x05, 0x7b, 0xf8, 0x8e, 0xe0, 0x03, 0x3e, 0x45, 0xa5, 0x8b, 0x81, 0x14, 0x75, 0xd1, 0xec,
	0xf7, 0xb3, 0xc4, 0xe7, 0xa8, 0x92, 0xc6, 0x39, 0x30, 0x64, 0x37, 0x99, 0x99, 0xe6, 0x97, 0xf6,
	0xed, 0x9d, 0x94, 0x75, 0xd1, 0x1c, 0xf6, 0xb3, 0xa4, 0xd7, 0xe8, 0x64, 0x4d, 0xf3, 0xd6, 0x68,
	0x0f, 0x98, 0xa0, 0xbd, 0x09, 0xb4, 0x17, 0x9f, 0x90, 0x23, 0xff, 0xb0, 0x7d, 0x5d, 0xab, 0x9f,
	0xc1, 0xfd, 0x28, 0x09, 0xb8, 0x43, 0x47, 0xf7, 0x52, 0x2a, 0xa3, 0xb3, 0x8f, 0x2f, 0xd9, 0xbf,
	0xad, 0x6c, 0x73, 0xe8, 0xc5, 0xd5, 0xf6, 0xcb, 0xa5, 0x97, 0xee, 0x3c, 0xd0, 0x97, 0x7a, 0x54,
	0xe1, 0x23, 0x0e, 0x4c, 0x9a, 0x89, 0x3f, 0x09, 0x1d, 0x63, 0x7b, 0x73, 0xcb, 0x83, 0x70, 0x20,
	0x5a, 0x9e, 0xfe, 0x62, 0xa8, 0xd2, 0x71, 0xf7, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x93, 0x64, 0x8f,
	0x72, 0x29, 0x01, 0x00, 0x00,
}
